import ErdosGyarfas.EqualityConclusion

/- Contract for the equality-case development. -/
#check ErdosGyarfas.EqualityIncidence.auxiliaryGraph
#check ErdosGyarfas.EqualityIncidence.auxiliaryGraph_four_regular
#check ErdosGyarfas.EqualityIncidence.auxiliaryGraph_noFourCycle
#check ErdosGyarfas.four_regular_noFourCycle_card_ge_thirteen
#check ErdosGyarfas.four_regular_noFourCycle_card_ge_fifteen_direct
#check ErdosGyarfas.EqualityIncidence.auxiliaryGraph_card_ge_fifteen
#check ErdosGyarfas.EqualityIncidence.equality_case_forty_five_direct
